### ISSUE TITLE
Issue with this block of code in the section "How to calculate uncertainty of the predictions"

### ISSUE THREAD

**Issue by diegozh7** [cmarti/gpmap-tools#1]
Issue with this block of code in the section "How to calculate uncertainty of the predictions"

              test = data.loc[np.isnan(data['y']), :].copy()
              test['pred'] = pred.loc[test.index, 'ypred'].values
              r2 = pearsonr(test['pred'], test['y_true'])[0] ** 2
              
              fig, axes = plt.subplots(1, 1, figsize=(4, 4))
              axes.scatter(x=test.y_true, y=test.pred, c='black', alpha=0.2, s=2)
              ticks = np.arange(-10, 9, 2)
              axes.set(xlabel=r'$y_{True}$', ylabel=r'$y_{pred}$', aspect=1,
                       xticks=ticks, yticks=ticks)
              axes.text(0.03, 0.97, r'$R^2$=' + '{:.3f}'.format(r2), transform=axes.transAxes,
                        va='top')
              axes.grid(alpha=0.2)

Long error with this at the end:
          KeyError: 'ypred'

**Comment by cmarti** [comment]
This was an issue with outdated documentation as the column names of the generated dataframes were updated:

Solved with commit 09bb2d6c48c5fbf8cdc129916b772937d5aca510
